### ISSUE TITLE
Failing to detect EC2 instances behind ELBv2 or ALB as exposed.

### ISSUE THREAD

**Issue by AlmogBaku** [lyft/cartography#1060] opened 2022-12-28 14:01 UTC
Cartography doesn't detect my ec2 instances as public, although they're exposed behind ELBv2 or ALB.

## Steps to reproduce
1. Create an ec2 node
2. Expose it via alb or elbv2
3. Scan the account using Cartography

## Why do we have this problem?
Apparently, the LoadBalancerV2 instances don't have a security group as the analysis job expects them to have:
https://github.com/lyft/cartography/blob/585fc0667feda4cf0d42ebe428cc3ab36fe6432e/cartography/data/jobs/analysis/aws_ec2_asset_exposure.json#L13

![Screenshot 2022-12-28 at 16 02 42](https://user-images.githubusercontent.com/98982/209823762-b24e8e77-433d-4aa2-b3d1-76b0502c974d.png)

**Comment by achantavy** [comment] 2023-01-26 01:29
Sorry for the late reply.

I'm not able to reproduce; the below query works for my environment:
```
MATCH (cidr:IpRange{range:'0.0.0.0/0'})—->(perm:IpPermissionInbound)—->(sg:EC2SecurityGroup)<-[:MEMBER_OF_EC2_SECURITY_GROUP]-(elbv2:LoadBalancerV2{scheme: 'internet-facing'})—->(listener:ELBV2Listener) WHERE listener.port>=perm.fromport AND listener.port<=perm.toport return * limit 10;
```

![image](https://user-images.githubusercontent.com/46503781/214735394-646d9159-46c3-43fc-83f5-5e04077d70ca.png)


The security groups are attached to the LoadBalancerV2s in this code: https://github.com/lyft/cartography/blob/c120a4aa2c07d1a711c0fdd10f3d6f87bfa33b64/cartography/intel/aws/ec2/load_balancer_v2s.py#L101-L115

I'd be curious in seeing the data being returned to this function in your case.

**Comment by achantavy** [comment] 2023-02-07 05:45
Going to close this out as it's been a while and I'm unable to reproduce, please re-open if you have more information.

**Closed by achantavy** 2023-02-07 05:45 UTC
