### ISSUE TITLE
Can't install / use cartography with Neo4j 4.4.8?

### ISSUE THREAD

**Issue by steve-solun** [lyft/cartography#893] opened 2022-08-07 17:14 UTC
*Description*:

I have installed 4.4.8 Neo4j [docker](https://hub.docker.com/layers/neo4j/library/neo4j/4.4.8-community/images/sha256-d7cb5bde33a15197f45ca2f8a701de059c9e33cc6b59a7d7a02c180462ea98c0?context=explore) and run 
```pip3 install cartography``` on my Mac M1.

Got the following error:
```
neo4j.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 2, column 26 (offset: 30))
"    MERGE (aa:AWSAccount{id: {ACCOUNT_ID}})"
```

*To Reproduce*:
1. Use OSX 12.5 Monterey (M1 MacBook Pro).
2. Install / pyenv python 3.8.9
3. docker run \
    --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=none \
    --volume=$HOME/neo4j/data:/data \
    neo4j:4.4.8-community
4. Try to run `cartography --neo4j-uri http://localhost:7474/`

You will get the following error log.

*Logs*:

```cartography --neo4j-uri bolt://localhost:7687                                     1 ✘ ╱ Knowledge_Graph-_87o5Pf9  ╱ at 16:34:40  
INFO:cartography.sync:Starting sync with update tag '1659879508'
INFO:cartography.sync:Starting sync stage 'create-indexes'
INFO:cartography.intel.create_indexes:Creating indexes for cartography node types.
INFO:cartography.sync:Finishing sync stage 'create-indexes'
INFO:cartography.sync:Starting sync stage 'aws'
INFO:cartography.intel.aws:Syncing AWS accounts: 564407622114
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 148, in _sync_multiple_accounts
    organizations.sync(neo4j_session, accounts, sync_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 119, in sync
    load_aws_accounts(neo4j_session, accounts, update_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 108, in load_aws_accounts
    neo4j_session.run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/simple.py", line 215, in run
    self._autoResult._run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 117, in _run
    self._attach()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 206, in _attach
    self._connection.fetch_message()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 188, in inner
    func(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 246, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 2, column 26 (offset: 30))
"    MERGE (aa:AWSAccount{id: {ACCOUNT_ID}})"
                              ^
Traceback (most recent call last):
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/bin/cartography", line 8, in <module>
    sys.exit(main())
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/cli.py", line 553, in main
    sys.exit(CLI(default_sync, prog='cartography').main(argv))
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/cli.py", line 533, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 163, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 148, in _sync_multiple_accounts
    organizations.sync(neo4j_session, accounts, sync_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 119, in sync
    load_aws_accounts(neo4j_session, accounts, update_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 108, in load_aws_accounts
    neo4j_session.run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/simple.py", line 215, in run
    self._autoResult._run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 117, in _run
    self._attach()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 206, in _attach
    self._connection.fetch_message()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 188, in inner
    func(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 246, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 2, column 26 (offset: 30))
"    MERGE (aa:AWSAccount{id: {ACCOUNT_ID}})"
```

>  - Cartography release version or commit hash: 3fa62ee2c07b92954ef5a4f4d039d4c94e918e85
>  - Python version: 3.8.9
>  - OS OSX 12.5 Monterey M1

**Comment by steve-solun** [comment] 2022-08-07 17:26
@ramonpetgrave64
@achantavy

**Comment by achantavy** [comment] 2022-08-07 17:58
Hi @steve-solun - as seen in the [install docs](https://lyft.github.io/cartography/install.html) ([permalink for future searchers](https://github.com/lyft/cartography/blob/95624b49787e238daa51476903a24b9d7cbb8c5d/docs/root/install.md), set the environment variable `EXPERIMENTAL_NEO4J_4X_SUPPORT=True` for Neo4 4.x to work.

Please give that a try and let us know if that helps!

We have a PR in progress to convert all the queries to the proper syntax but for now we have a solution that dynamically intercepts the database queries and adjusts them appropriately to the 4.x-style syntax if that env var is set. We've been running that for around a month ourselves on some real workloads.

**Comment by steve-solun** [comment] 2022-08-07 18:00
@achantavy  I did it on my MAC, should I do it inside the docker?
~/Library/Python/3.8/bin  echo $EXPERIMENTAL_NEO4J_4X_SUPPORT                                                                                       
True

**Comment by achantavy** [comment] 2022-08-07 18:01
>  should I do it inside the docker?

Yes

**Comment by steve-solun** [comment] 2022-08-07 18:03
Maybe you can add it inside your dockerfile? 
I am using Neo4j Docker, not yours.

I am using 4.4.5 Neo4j and it works (I still need some permissions from my AWS admin, but at least I don't have such issues).

**Comment by achantavy** [comment] 2022-08-07 18:18
Ah ok, sorry I misread your original post and thought you were running the cartography Dockerfile and not the Neo4j Dockerfile. The machine that is running the `cartography` CLI command should have that `EXPERIMENTAL_NEO4J_4X_SUPPORT` environment variable set to `True`.

The stack trace that you posted seems to indicate that our syntax autopatcher has not taken effect so I don't think the env var was set for that run (unless we have a bug). 

> I am using 4.4.5 Neo4j and it works

Just to clarify, are you saying that cartography works on Neo4j 4.4.5 but not 4.4.8?

Is cartography still not working for you? If you got things working then please post back with what you did to fix it.

**Comment by steve-solun** [comment] 2022-08-07 18:42
@achantavy yes it works (still not fully cuz I need my AWS admin to give me more permissions) but yes it works with 4.4.5.
I think we can arrange a quick call to have a look, I am a technical user but maybe others are less and it will be better to provide a tool that actually works.
I am open to schedule a call so you will see what is going on.

**Comment by steve-solun** [comment] 2022-08-07 18:44
@achantavy + running `cartography --neo4j-uri bolt://localhost:7687`
returns an error (when running from the Mac terminal):

zsh: command not found: cartography

**Comment by achantavy** [comment] 2022-08-07 19:04
There's multiple things going on so let's try to attack them one by one.

1. It works when you `cd` to the directory, but nowhere else.

I was unable to repro this just now. I created a brand new Python venv with

```
➜  mkvirtualenv 2022-aug-7
created virtual environment CPython3.9.13.final.0-64 in 379ms
  creator CPython3Posix(dest=/Users/achantavy/.virtualenvs/2022-aug-7, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/achantavy/Library/Application Support/virtualenv)
    added seed packages: pip==22.1.2, setuptools==63.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /Users/achantavy/.virtualenvs/2022-aug-7/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/achantavy/.virtualenvs/2022-aug-7/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/achantavy/.virtualenvs/2022-aug-7/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/achantavy/.virtualenvs/2022-aug-7/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/achantavy/.virtualenvs/2022-aug-7/bin/get_env_details
```

To show this is a fresh venv, cartography is not available as expected:
```
(2022-aug-7) ➜  ~ which cartography
cartography not found
```

Then I install it with
```
(2022-aug-7) ➜  ~ pip install cartography
```


(2022-aug-7) ➜  ~ pip freeze | grep cartography
cartography==0.63.0

**Comment by steve-solun** [comment] 2022-08-07 19:08
@achantavy 
Same here:
pip3 freeze | grep cartography
cartography==0.63.0

Now I am in my home directory:
cartography -h
zsh: command not found: cartography

**Comment by steve-solun** [comment] 2022-08-07 19:08
which cartography
cartography not found

**Comment by steve-solun** [comment] 2022-08-07 19:09
@achantavy I am on your slack channel, maybe you want to make a quick call?

**Comment by achantavy** [comment] 2022-08-07 19:23
Please try create a new virtualenv to use for only cartography and then
follow the steps I showed in my last comment. I personally like
virtualenvwrapper but you can use what works for you. Oh and just to rule
things out, I'm using python 3.8 but newer ones are probably fine too.

Oh, and yeah the describe regions failure is an aws permissions issue -
your IAM role needs at minimum AWS' built-in SecurityAudit policy.

**Comment by steve-solun** [comment] 2022-08-07 19:25
@achantavy I am using pyenv and pipenv for this.
Python 3.8.9

**Comment by steve-solun** [comment] 2022-08-07 20:11
@achantavy please have a look:

cartography issue works now, but I get the same error with 4.4.5 now:

```
cartography --neo4j-uri bolt://localhost:7687
INFO:cartography.sync:Starting sync with update tag '1659902864'
INFO:cartography.sync:Starting sync stage 'create-indexes'
INFO:cartography.intel.create_indexes:Creating indexes for cartography node types.
INFO:cartography.sync:Finishing sync stage 'create-indexes'
INFO:cartography.sync:Starting sync stage 'aws'
INFO:cartography.intel.aws:Syncing AWS accounts: 564407622114
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 148, in _sync_multiple_accounts
    organizations.sync(neo4j_session, accounts, sync_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 119, in sync
    load_aws_accounts(neo4j_session, accounts, update_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 108, in load_aws_accounts
    neo4j_session.run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/simple.py", line 215, in run
    self._autoResult._run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 117, in _run
    self._attach()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 206, in _attach
    self._connection.fetch_message()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 188, in inner
    func(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 246, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 2, column 26 (offset: 30))
"    MERGE (aa:AWSAccount{id: {ACCOUNT_ID}})"
                              ^
Traceback (most recent call last):
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/bin/cartography", line 33, in <module>
    sys.exit(load_entry_point('cartography==0.63.0', 'console_scripts', 'cartography')())
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/cli.py", line 553, in main
    sys.exit(CLI(default_sync, prog='cartography').main(argv))
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/cli.py", line 533, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 163, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/sync.py", line 85, in run
    stage_func(neo4j_session, config)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 237, in start_aws_ingestion
    sync_successful = _sync_multiple_accounts(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 148, in _sync_multiple_accounts
    organizations.sync(neo4j_session, accounts, sync_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/util.py", line 131, in timed
    return method(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 119, in sync
    load_aws_accounts(neo4j_session, accounts, update_tag, common_job_parameters)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/cartography/intel/aws/organizations.py", line 108, in load_aws_accounts
    neo4j_session.run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/simple.py", line 215, in run
    self._autoResult._run(
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 117, in _run
    self._attach()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/work/result.py", line 206, in _attach
    self._connection.fetch_message()
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 188, in inner
    func(*args, **kwargs)
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/Users/stevesolun/.local/share/virtualenvs/Knowledge_Graph-_87o5Pf9/lib/python3.8/site-packages/neo4j/io/_common.py", line 246, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 2, column 26 (offset: 30))
"    MERGE (aa:AWSAccount{id: {ACCOUNT_ID}})"
```


Here is my Neo4j docker:

```
docker run \ 
    --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=none \
    --volume=$HOME/neo4j/data:/data \
    neo4j:4.4.5-community
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
2022-08-07 20:07:36.268+0000 INFO  Starting...
2022-08-07 20:07:36.505+0000 INFO  This instance is ServerId{e7bb7f3d} (e7bb7f3d-9df4-4d60-a80d-f702d23563c8)
2022-08-07 20:07:37.099+0000 INFO  ======== Neo4j 4.4.5 ========
2022-08-07 20:07:38.511+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
2022-08-07 20:07:38.517+0000 INFO  Setting up initial user from defaults: neo4j
2022-08-07 20:07:38.517+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=true, suspended=false)
2022-08-07 20:07:38.529+0000 INFO  Setting version for 'security-users' to 3
2022-08-07 20:07:38.531+0000 INFO  After initialization of system graph model component 'security-users' have version 3 and status CURRENT
2022-08-07 20:07:38.535+0000 INFO  Performing postInitialization step for component 'security-users' with version 3 and status CURRENT
2022-08-07 20:07:39.039+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2022-08-07 20:07:39.463+0000 INFO  Remote interface available at http://localhost:7474/
2022-08-07 20:07:39.465+0000 INFO  id: 35B68951F5E580E7C412D82E8C8E438D1F8A7AE4C58B57C1227D7E0D988FC73E
```

**Comment by achantavy** [comment] 2022-08-08 03:10
I'm having a hard time reproducing your issue unfortunately. In the meantime I'll try to summarize general tips on getting a test env set up that'll hopefully unblock you:

- Use a new venv for cartography. Make sure you are running Python 3.8. Newer versions of Python will probably work; we hear of other users running 3.10 with no problems.
- Install cartography on the venv with `pip install cartography`. Make sure that `pip freeze | grep cartography` outputs `cartography==0.63.0`
- For neo4j 4.x support, the user on the machine that you are running cartography with must have the `EXPERIMENTAL_NEO4J_4X_SUPPORT` environment variable set to `True`.
- There should not be any meaningful differences between running cartography against Neo4j 4.4.5 or 4.4.8; simply ensure the env var described above is set so that our syntax autopatcher works.
- If you are having troubles with the Neo4j docker container, consider running the Neo4j DB itself on your laptop: it's fairly simple, just unzip a tar,`cd /path/to/neo4j`, edit conf/neo4j.conf to turn off auth for testing, and run `/bin/neo4j console` to start the server. To uninstall you can just delete the directory. Up to you though, using docker or not is a personal preference.

If what I've described is not correct, please reply with exact steps to reproduce your issue and we can dive in more thoroughly during the work week.

**Comment by steve-solun** [comment] 2022-08-08 07:16
@achantavy thanks a lot! Will try and report.
Please guide how to install the Java for Neo4j and config the relevant variables on Mac OSX 12.5 M1, if possible for those who will install Neo4j on their laptops.

**Comment by achantavy** [comment] 2022-08-08 17:55
On Mac I personally like using `brew install adoptopenjdk11` to install Java 11, but I am not a Java expert so whatever works for you is probably fine.

Based on this [Slack thread](https://lyftoss.slack.com/archives/CTZUQL0KX/p1659948337904649?thread_ts=1659944357.996669&cid=CTZUQL0KX),

> I have figured it out together with Alex. [...] I have installed the Neo4j docker, installed the cartography package in a virtualenv using pipenv and exported the variable they asked.

it sounds like you've got everything working.

Are there areas of the docs that we should explain better? List them out and we'll try to improve it.

**Comment by steve-solun** [comment] 2022-08-09 09:02
Hey @achantavy sure, actually a few.
I am open to make a call with you to show you all the relevant places if you don't mind.
I am a tech person but I needed almost a day to figure out the technicalities.
Can we schedule a call on slack?

**Comment by achantavy** [comment] 2022-08-09 14:35
We'd happily accept a PR to update the docs, or if you're not able to then listing out the places that slowed you down here would help us out a lot.

We also have our community meeting at the end of the month if you wanted to talk synchronously.

**Comment by steve-solun** [comment] 2022-08-10 16:42
Dear @achantavy please invite me to this meeting, will be happy to talk. 
Generally speaking, I would like to see a Step by Step tutorial to install and run the solution. We have changed the docker-compose file and it works for us but it's worth to make it universal.

**Comment by achantavy** [comment] 2022-08-10 17:31
The install docs are [here](https://lyft.github.io/cartography/install.html) ([permalink](https://github.com/lyft/cartography/blob/95624b49787e238daa51476903a24b9d7cbb8c5d/docs/root/install.md)), the operations docs are [here](https://lyft.github.io/cartography/ops.html?highlight=operations) ([permalink](https://github.com/lyft/cartography/blob/08b8b1e616a77a8ec04b0d5eafbadec169afde29/docs/root/ops.md)). They are intended to be a step by step tutorial but definitely can be improved. Again, I'm happy to accept any PR to update these with your findings - I think others would benefit from your experience.

Details on our community meeting are here: https://github.com/lyft/cartography#community-meeting, there's also a Google calendar schedule there that you can follow.

Thanks for asking the detailed question so that others can find this issue and hopefully follow along :) I'm going to close this out since it sounds like you've gotten it working.

**Closed by achantavy** 2022-08-10 17:31 UTC
